version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:8.8.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      # Since ES 8, SSL is on by default, disabling on local
      - xpack.security.enabled=false